Better exception message for when default value is an enum
Roave/BetterReflection pull request #1380
Opened 2023-11-22 21:18 UTC by forrest79

This solves an issue #1376.

2023-11-24 18:28 UTC, Ocramius requested changes

2023-11-24 18:28 UTC, Ocramius commented on test/unit/NodeCompiler/CompileNodeToValueTest.php
> +        $this->expectException(UnableToCompileNode::class);
We should check at least part of the exception message in this test: it seems like the mutation test reports no behavioral change (removes `throw` and is happy with that), which indicates that an assertion is to be added here

2023-12-04 23:12 UTC, forrest79 commented
Sorry for a delay, I was working remotely for a couple of days. I added a message check. You can look at it.

2023-12-04 23:41 UTC, Ocramius requested changes
CS issues fixable with some minimal assertion improvements (by removing try-catch)

2023-12-04 23:41 UTC, Ocramius commented on test/unit/NodeCompiler/CompileNodeToValueTest.php
> +            self::assertStringContainsString('An enum expression Foo::ONE is not supported in class Bat in file ', $e->getMessage());
Can use `expectExceptionMessage`, rather than adding a try-catch 😁

2023-12-06 22:44 UTC, forrest79 commented on test/unit/NodeCompiler/CompileNodeToValueTest.php
> +            self::assertStringContainsString('An enum expression Foo::ONE is not supported in class Bat in file ', $e->getMessage());
Done

2023-12-06 23:16 UTC, Ocramius commented
I think the failures are unrelated to your patch, and instead depend on https://github.com/shivammathur/setup-php/issues/799

2023-12-06 23:17 UTC, Ocramius approved these changes
LGTM, thanks @forrest79!

I will re-run tests and merge once the upstream issue with the CI pipeline is resolved, then releasing :muscle:

2023-12-06 23:18 UTC, Ocramius commented
Needs https://github.com/shivammathur/php-ubuntu/pull/3

2023-12-07 10:58 UTC, Ocramius approved these changes
Excellent, thanks @forrest79!

2023-12-07 10:58 UTC, merged