One reflector to rule them all
Roave/BetterReflection pull request #772
Opened 2021-09-18 22:18 UTC by kukulich

One reflector to rule them all
one reflector to find them
one reflector to bring them all
and in the reflection bind them

2021-09-18 22:50 UTC, kukulich commented
This is PoC of big BC break :)

Motivation:

```php
<?php

namespace Foo;

const SOME_CONSTANT = 0;

class Boo
{
     public function method($parameter = SOME_CONSTANT)
     {}
}
```
It's not possible with `ClassReflector` and `StringSourceLocator`/`SingleFileSourceLocator` to resolve default value of the parameter.
`ClassReflector` can create the `ReflectionClass` but it's not possible to get the default value because it has to be resolved by `ConstantReflector` and there's no `ConstantReflector` in the `ReflectionClass`.  It only partly works thanks to `CompileNodeToValue` and global functions `defined` and `constant`.

I propose to have one `Reflector` that can resolve everything based on the `SourceLocator`.

It can also improve the types. There are a lot of places where current interface `Reflector` is as the parameter but we almost everytime expect that it's `ClassReflector`.

I've also removed the ugly circular reference in https://github.com/Roave/BetterReflection/blob/5.0.x/src/BetterReflection.php#L89

---

There's one class `Reflector` in the PR but it should be `interface` and there should be one implementation, eg. `BetterReflector`, `OneReflector (as 1Password) or any other name. Or the interface can be eg. `ReflectorInterface`.

2021-09-19 16:27 UTC, kukulich commented
@Ocramius Please look at this PR (when you have time) and tell me if it will be mergeable :) If yes, please also add the opinion about the names :) I’ll then make the build green.

2021-09-21 08:11 UTC, asgrim reviewed
The concept here seems fine; there is a finite number of "types of symbols to reflect on" so growth is reasonably controlled, I think our concern originally (why we split into `ClassReflector`/`FunctionReflector`) is uncertainty over how many symbol types we'd want to reflect about. Now the library is much more defined, it seems reasonable.

I do also like that it solves the circular dependency issue :+1:

2021-09-21 08:13 UTC, asgrim commented
> There's one class `Reflector` in the PR but it should be `interface` and there should be one implementation, eg. `BetterReflector`, `OneReflector (as 1Password) or any other name. Or the interface can be eg. `ReflectorInterface`.

I'd say keep the interface named `Reflector` (this becomes clear where the BC break is then - because the interface is changed, rather than changing interface into a class). For the implementation name I'm not worried about, maybe `BetterReflector` is fine, but I'll let @Ocramius opine later on that :grin:

2021-09-26 14:25 UTC, Ocramius requested changes
@kukulich from my PoV, approach is very much valid! It's a major BC break, but easy to migrate to it

2021-09-26 14:25 UTC, Ocramius commented on src/Reflector/Reflector.php
> +     * @return ReflectionClass[]
Since the signature changed, I think it might be a good idea to return an `iterable` here for future-proofing our ability to use a lazy iterator

2021-09-26 14:25 UTC, Ocramius commented on src/Reflector/Reflector.php
> +     * @return ReflectionFunction[]
Since the signature changed, I think it might be a good idea to return an `iterable` here for future-proofing our ability to use a lazy iterator

2021-09-26 14:25 UTC, Ocramius commented on src/Reflector/Reflector.php
> +     * @return array<int, ReflectionConstant>
Since the signature changed, I think it might be a good idea to return an `iterable` here for future-proofing our ability to use a lazy iterator

2021-09-26 15:16 UTC, kukulich commented
@Ocramius what do you think about the names of interface and the class?

2021-10-11 14:57 UTC, kukulich commented
@Ocramius @asgrim Could you please give me a clue about the class and interface names? :) This PR blocks other my PR.

2021-10-11 15:01 UTC, Ocramius commented
@kukulich `Reflector` for the interface, `DefaultReflector` for the implementation? WDYT?

`DefaultReflector` could also be `SourceLocatorBasedReflector` or such, but IMO not that important there.

2021-10-11 15:59 UTC, kukulich commented
@Ocramius @asgrim Ready to review :)

2021-10-11 16:25 UTC, Ocramius requested changes
One last change needed :D

2021-10-11 16:25 UTC, Ocramius commented on src/Reflector/DefaultReflector.php
> +class DefaultReflector implements Reflector
We should make this `final`

2021-10-11 16:38 UTC, Ocramius approved these changes
:ship:

2021-10-11 17:14 UTC, merged

2021-10-11 17:14 UTC, Ocramius commented
Awesome, thanks @kukulich!