Add `ReflectionParameter::hasType()`
Roave/BetterReflection pull request #792
Opened 2021-10-03 00:48 UTC by WinterSilence

2021-10-03 05:12 UTC, Ocramius requested changes
This kind of change requires test additions to validate it

2021-10-11 13:36 UTC, asgrim requested changes

2021-10-11 13:36 UTC, asgrim commented on src/Reflection/ReflectionParameter.php
> +     * Checks parameter type.
```suggestion
     * Checks if a parameter has the type specified in `$type`
```
or something similar? Just need something more descriptive

2021-10-11 13:36 UTC, asgrim commented on src/Reflection/ReflectionParameter.php
> +        $this->isArray = null;
As these values are memoized, we either need to:

 * Remove the memoization of the `isArray` / `isCallable` checks
 * Add a test case that ensure memoization recalls the value, and also is reset when type is removed

2021-10-11 13:36 UTC, asgrim commented on src/Reflection/ReflectionParameter.php
> +        $this->removeType();
As the checks are memoized, we either need to:

 * Remove the memoization of the `isArray` / `isCallable` checks
 * Add a test case to ensure that memoization is removed when setting a new type of the parameter

2021-10-11 13:36 UTC, asgrim commented on src/Reflection/ReflectionParameter.php
> +        $aliases = ['boolean' => 'bool', 'integer' => 'int', 'double' => 'float', 'NULL' => 'null'];
Could possibly be defined in a `private const`?

2021-10-11 13:36 UTC, asgrim commented on src/Reflection/ReflectionParameter.php
> +            foreach ($paramTypes as $paramType) {
`$paramType` is redefined here (originally declared on L505), slightly confusing naming re-use.

2021-10-11 13:36 UTC, asgrim commented on test/unit/Reflection/ReflectionParameterTest.php
> +    public function testHasType(): void
Think this test could be improved by adding a `@dataProvider` and checking every possible type we can. I worry that some types might trip this up without test cases proving otherwise

2021-10-11 13:37 UTC, asgrim commented
> also it's fix invalid result of isArray/isCallable for union type

A separate test case should be added to verify the original bug is also fixed.

2021-10-11 18:10 UTC, kukulich commented on src/Reflection/ReflectionParameter.php
> +    public function hasType(string|ReflectionNamedType $type, bool $ignoreDefaultValue = false): bool
The method `hasType` already exists: https://github.com/Roave/BetterReflection/blob/5.0.x/src/Reflection/ReflectionParameter.php#L386

2021-10-12 11:41 UTC, WinterSilence commented on src/Reflection/ReflectionParameter.php
> +        $aliases = ['boolean' => 'bool', 'integer' => 'int', 'double' => 'float', 'NULL' => 'null'];
@asgrim I'm don't see reason for this now

2021-10-12 11:46 UTC, WinterSilence commented on src/Reflection/ReflectionParameter.php
> +            foreach ($paramTypes as $paramType) {
@asgrim I just ran out of ideas for variable names (:

2021-10-12 11:52 UTC, WinterSilence commented on src/Reflection/ReflectionParameter.php
> +    public function hasType(string|ReflectionNamedType $type, bool $ignoreDefaultValue = false): bool
@asgrim can you comment this? i can update method ` public function hasType(string|ReflectionNamedType $type = null, bool $ignoreDefaultValue = false): bool` to keep LSP

2021-10-12 15:06 UTC, closed without merging

2021-10-12 15:07 UTC, Ocramius commented
@WinterSilence I've merged #803, which includes these changes - can you give it a shot and see if it works for you?

2021-10-12 15:33 UTC, WinterSilence commented
@Ocramius copying my changes without merging PR is not so friendly

2021-10-12 16:43 UTC, Ocramius commented
> @Ocramius #803 not same to current PR, only define method with same name


@WinterSilence if it's not the same scenario, I'd gladly adjust: does your test case still fail?

 > @Ocramius it's bad habit to close PR without understanding it

PR got closed by merge via `Fixes X` comment provided by @kukulich: @kukulich did put in the time to understand your work. Please don't assume malice.

 > @Ocramius copying my changes without merging PR is not so friendly

No copying, AFAIK - this was done in a different way, from what I see from the diff. Again, please don't assume malice: we're really just trying to improve the codebase, all of us in our free time, I'd add.