Improved "deprecated" support to work with internal classes and PHP version constraints
Roave/BetterReflection pull request #801
Opened 2021-10-11 16:31 UTC by kukulich

The "deprecated" support is provided by the `@deprecated` annotation. There was already support for it, so I've just extend it.

There's just one disadvantage - the doccomment is not the same that is in the stubs but I don't think it's an issue for internal stubs.

---

There's another possible solution. The support can be provided by special BR `Deprecated` attribute that will be added in `ReflectionSourceStubber` or `PhpStormSourceStubber`.

Advantages:
- The doccomment will be untouched
- The attribute can be easily filtered in future `getAttributes()` methods so we can ignore it where we want.
- It allows to support even deprecated parameters: https://github.com/JetBrains/phpstorm-stubs/blob/master/Core/Core.php#L343

Waiting for ideas/thoughts :)

2021-10-12 15:39 UTC, Ocramius requested changes

2021-10-12 15:39 UTC, Ocramius commented on src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
> +    private function isDeprecatedInPhpVersion(Node\Stmt\ClassLike|Node\Stmt\ClassConst|Node\Stmt\Property|Node\Stmt\ClassMethod|Node\Stmt\Function_ $node): bool
Elaborate :O

2021-10-12 15:39 UTC, Ocramius commented on src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
> +            ($reflection instanceof CoreReflectionMethod || $reflection instanceof CoreReflectionFunction)
Is deprecation not existing at class level?

2021-10-12 15:39 UTC, Ocramius commented on src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
> +        if ($docComment === false) {
Are we 100% sure that `$reflection->getDocComment()` never returns anything for core methods?

2021-10-12 15:39 UTC, Ocramius commented on src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
> +            ($reflection instanceof CoreReflectionMethod || $reflection instanceof CoreReflectionFunction)
Properties also seem to be skipped here :thinking:

2021-10-12 15:39 UTC, Ocramius commented on test/unit/Reflection/ReflectionConstantTest.php
> +                  * @deprecated since 8.0
I didn't even know this was a thing :O

2021-10-12 15:40 UTC, kukulich commented on src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
> +            ($reflection instanceof CoreReflectionMethod || $reflection instanceof CoreReflectionFunction)
Yes, `isDeprecated()` method exists only for functions/methods in native reflection.

2021-10-12 15:42 UTC, kukulich commented on src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
> +        if ($docComment === false) {
Please see the description of this PR. There's another option :)

However I can do here the same as I did in PhpStormSourceStubber - I can modify the comment when exists.

2021-10-12 15:43 UTC, Ocramius commented
> here's just one disadvantage - the doccomment is not the same that is in the stubs but I don't think it's an issue for internal stubs.

Not a big deal: internal stubs are not really in use by anyone so far, AFAIK.

If we need parity on internal methods too, we can improve/iterate on that

2021-10-12 16:03 UTC, Ocramius commented on src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
> +        if ($docComment === false) {
> I can modify the comment when exists.

Would be fine by me, but IMO overkill.

This is already a good improvement, so we should roll with it for now

2021-10-12 16:52 UTC, kukulich commented
@Ocramius Is it something I should fix here? I'm not able to find anything...

2021-10-12 16:59 UTC, asgrim commented on src/Reflection/Deprecated/DeprecatedHelper.php
> +    public static function isDeprecated(string $docComment): bool
Hm - would be nice if we can make this `@psalm-pure` if it is `static`, although I'm not sure if `DocBlockFactory::createInstance` is pure itself

2021-10-12 17:01 UTC, kukulich commented on src/Reflection/Deprecated/DeprecatedHelper.php
> +    public static function isDeprecated(string $docComment): bool
I can remove `DocBlockFactory` completely. It can be easy regexp I suppose...

2021-10-13 12:43 UTC, Ocramius commented on src/Reflection/Deprecated/DeprecatedHelper.php
> +    public static function isDeprecated(string $docComment): bool
We can mark it `@psalm-pure` and then use an inline suppression after inspection of `DocblockFactory`.

At first glance, `DocblockFactory` seems quite safe to use, when isolated this way: https://github.com/phpDocumentor/ReflectionDocBlock/blob/0005eb9eaecc2a3a00b8ee34c06643a316ebb228/src/DocBlockFactory.php

2021-10-13 13:18 UTC, kukulich commented on src/Reflection/Deprecated/DeprecatedHelper.php
> +    public static function isDeprecated(string $docComment): bool
So should I suppress everything?

```
ERROR: ImpureStaticProperty - src/Reflection/Deprecated/DeprecatedHelper.php:25:9 - Cannot use a static property in a mutation-free context (see https://psalm.dev/221)
        self::$docBlockFactory ??= DocBlockFactory::createInstance();


ERROR: ImpureMethodCall - src/Reflection/Deprecated/DeprecatedHelper.php:25:53 - Cannot call an impure method from a pure context (see https://psalm.dev/203)
        self::$docBlockFactory ??= DocBlockFactory::createInstance();


ERROR: ImpureStaticProperty - src/Reflection/Deprecated/DeprecatedHelper.php:27:21 - Cannot use a static property in a mutation-free context (see https://psalm.dev/221)
        $docBlock = self::$docBlockFactory->create($docComment);


ERROR: ImpureMethodCall - src/Reflection/Deprecated/DeprecatedHelper.php:27:45 - Cannot call a non-mutation-free method phpDocumentor\Reflection\DocBlockFactory::create from a pure context (see https://psalm.dev/203)
        $docBlock = self::$docBlockFactory->create($docComment);


ERROR: ImpureMethodCall - src/Reflection/Deprecated/DeprecatedHelper.php:29:27 - Cannot call a non-mutation-free method phpDocumentor\Reflection\DocBlock::hasTag from a pure context (see https://psalm.dev/203)
        return $docBlock->hasTag('deprecated');
```

2021-10-13 14:37 UTC, Ocramius commented on src/Reflection/Deprecated/DeprecatedHelper.php
> +    public static function isDeprecated(string $docComment): bool
I'd say so - all of this is literally in-memory operations on a `string`

2021-10-13 14:51 UTC, kukulich commented on src/Reflection/Deprecated/DeprecatedHelper.php
> +    public static function isDeprecated(string $docComment): bool
https://github.com/Roave/BetterReflection/pull/801/commits/9221c327a3c47b4002a532078f632bd8903454b6

2021-10-13 15:09 UTC, merged

2021-10-13 15:09 UTC, Ocramius commented
Thanks @kukulich! :+1: