`AutoloadSourceLocator` now supports class aliases
Roave/BetterReflection pull request #802
Opened 2021-10-11 21:43 UTC by kukulich

Fixes https://github.com/Roave/BetterReflection/issues/616

2021-10-12 15:19 UTC, Ocramius requested changes

2021-10-12 15:19 UTC, Ocramius commented on src/SourceLocator/Located/AutoloadLocatedSource.php
> +    public function getOriginalName(): ?string
We should probably document what `getOriginalName()` means

2021-10-12 15:19 UTC, Ocramius commented on src/SourceLocator/Located/LocatedSource.php
> +    public function getOriginalName(): ?string
We should probably document what `getOriginalName()` means

2021-10-12 15:19 UTC, Ocramius commented on src/SourceLocator/Located/LocatedSource.php
> +        return null;
Is this supposed to be `null`? It's a bit unclear from a reader's perspective why the main `LocatedSource` (used in most places) would miss a `getOriginalName()` :thinking:

2021-10-12 15:19 UTC, Ocramius commented on src/SourceLocator/Located/AutoloadLocatedSource.php
> +class AutoloadLocatedSource extends LocatedSource
A class-level description of `AutoloadedLocatedSource` vs `LocatedSource` would go a long way :D

2021-10-12 15:31 UTC, kukulich commented on src/SourceLocator/Located/LocatedSource.php
> +        return null;
I can make it non-optional and rename it to eg. `getLocatedName()` ? It just means we will ignore `$identifier->getName()` here: https://github.com/Roave/BetterReflection/pull/802/files#diff-13cc5d496e14b9c4570202c9c30411d7fb5d57928344c388247f7b8754c4085dR84

2021-10-12 15:47 UTC, Ocramius commented on src/SourceLocator/Located/LocatedSource.php
> +        return null;
IMO, if it is not an alias, `getName()` and `getOriginalName()` are supposed to be the same.

2021-10-12 15:48 UTC, Ocramius commented on src/SourceLocator/Located/LocatedSource.php
> +        return null;
Perhaps we can make a `AliasLocatedSource {private $aliasName; private LocatedSource $actualSource; }` as a more semantically understandable construct: the main reason for my comments on this patch are around structural understanding/naming

2021-10-12 16:57 UTC, asgrim approved these changes

2021-10-12 16:57 UTC, kukulich commented on src/SourceLocator/Located/LocatedSource.php
> +        return null;
@Ocramius There's no `LocatedSource` interface so I suppose I cannot create `AliasLocatedSource {private $aliasName; private LocatedSource $actualSource; }` but I can probably create `AliasLocatedSource` instead of `AutoloadLocatedSource`. I'll try something.

2021-10-12 18:18 UTC, kukulich commented
@Ocramius New version forcepushed.

2021-10-13 12:46 UTC, Ocramius approved these changes
Looking much better now! Besides a missing `/** @internal */`, this can be :ship: -ed

2021-10-13 12:46 UTC, Ocramius commented on src/SourceLocator/Located/AnonymousLocatedSource.php
> +class AnonymousLocatedSource extends LocatedSource
Should still be `/** @internal */`

2021-10-13 12:59 UTC, kukulich commented on src/SourceLocator/Located/AnonymousLocatedSource.php
> +class AnonymousLocatedSource extends LocatedSource
`LocatedSource` is `@internal` so I thought it's enough but done :) https://github.com/Roave/BetterReflection/pull/802/commits/b848b4f86857f5d7970707f6c4276ae27ee75647

2021-10-13 13:07 UTC, Ocramius commented on src/SourceLocator/Located/AnonymousLocatedSource.php
> +class AnonymousLocatedSource extends LocatedSource
All shall be noticed

![lor-lord-of-the-rings](https://user-images.githubusercontent.com/154256/137138616-8f9996f1-fa15-4873-bfd4-114deb290505.gif)

2021-10-14 11:23 UTC, merged