PhpStormStubsSourceStubber: `@since` and `@removed` annotations in some cases do not contain a PHP version, but an extension version - e.g. "@since 1.3.0"
Roave/BetterReflection pull request #809
Opened 2021-10-13 09:30 UTC by kukulich

2021-10-13 16:26 UTC, Ocramius requested changes
Diff seems OK (no evident defects), but I really don't understand the commit message (PR title)

2021-10-13 16:26 UTC, Ocramius commented on src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
> +        'Zend OPcache',
The naming convention across extension is... "sub-optimal" to say it nicely :D

2021-10-13 16:26 UTC, Ocramius commented on test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
> +            ['RADIUS_DISCONNECT_ACK', null, true],
/cc @asgrim look who's back :D

2021-10-13 16:26 UTC, Ocramius commented on src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
> +        // We have to check "@since" and "@remove" only for core extensions because there's version of extension for other extensions
I really don't understand this comment :-\

2021-10-13 16:28 UTC, kukulich commented on src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
> +        // We have to check "@since" and "@remove" only for core extensions because there's version of extension for other extensions
https://github.com/JetBrains/phpstorm-stubs/blob/master/radius/radius.php#L50

It's not PHP version, it's version of the extension.

Yeah, my english is bad...

2021-10-13 16:41 UTC, kukulich commented on src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
> +        // We have to check "@since" and "@remove" only for core extensions because there's version of extension for other extensions
Improved.

2021-10-14 11:22 UTC, Ocramius approved these changes
Now I understand this diff, thanks :D

2021-10-14 11:22 UTC, Ocramius commented on src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
> +        // We have to check "@since" and "@remove" only for core extensions because there's version of extension for other extensions
@kukulich at least the code is impeccable ;-)

2021-10-14 11:22 UTC, merged