PHP 8.1: Intersection types
Roave/BetterReflection pull request #818
Opened 2021-10-13 20:08 UTC by kukulich

2021-10-14 18:34 UTC, Ocramius requested changes

2021-10-14 18:34 UTC, Ocramius commented on infection.bootstrap.php
> +require __DIR__ . '/stubs/ReflectionIntersectionType.php';
What is going on here exactly? :thinking:

2021-10-14 18:36 UTC, kukulich commented on infection.bootstrap.php
> +require __DIR__ . '/stubs/ReflectionIntersectionType.php';
It fails on PHP 8.0 because there's no `ReflectionIntersectionType`.

2021-10-14 18:43 UTC, Ocramius requested changes

2021-10-14 18:43 UTC, Ocramius commented on src/Reflection/Adapter/ReflectionProperty.php
> +    public function getType(): ReflectionUnionType|ReflectionNamedType|ReflectionIntersectionType|null
Sneaky `ReflectionType` was still there!

2021-10-14 18:43 UTC, Ocramius commented on infection.bootstrap.php
> +require __DIR__ . '/stubs/ReflectionIntersectionType.php';
Looking at this, what happens if userland attempts to use the `ReflectionIntersectionType` (adapter) on PHP 8.0?

2021-10-14 18:43 UTC, Ocramius commented on src/Reflection/ReflectionIntersectionType.php
> +        return implode('&', array_map(static fn (ReflectionNamedType $type): string => (string) $type, $this->types));
Let's avoid `(string) $type` and use `$type->__toString()` or such instead

2021-10-14 18:43 UTC, Ocramius commented on src/Reflection/ReflectionParameter.php
> +        if ($typeReflection instanceof ReflectionIntersectionType) {
`isCallable()` could potentially return `true` if multiple types implement `__invoke` here

2021-10-14 18:43 UTC, Ocramius commented on stubs/ReflectionIntersectionType.php
> +if (PHP_VERSION_ID < 80100) {
Given the `class_exists()`, do we need `PHP_VERSION_ID` at all?

2021-10-14 18:51 UTC, kukulich commented on infection.bootstrap.php
> +require __DIR__ . '/stubs/ReflectionIntersectionType.php';
Yes, I'm not sure if the stub should not be part of the adapter...

2021-10-14 18:58 UTC, kukulich commented on src/Reflection/ReflectionParameter.php
> +        if ($typeReflection instanceof ReflectionIntersectionType) {
https://3v4l.org/jVEkA

I think we have this method only for adapters so I would not return something not compatible with native reflection.

2021-10-22 08:33 UTC, Ocramius approved these changes
LGTM :+1:

2021-10-22 08:33 UTC, merged

2021-10-22 08:33 UTC, Ocramius commented
Thanks @kukulich!

2021-10-22 08:34 UTC, kukulich commented
Thanks to @WyriHaximus as well :)

2021-10-24 18:27 UTC, WyriHaximus commented
Thanks @kukulich, haven't been able to put the amount of time into this as I wanted, but you done an awesome job here and in the other PR's 🚀 !