PHP 8.1: Implemented `new` in initializers
Roave/BetterReflection pull request #819
Opened 2021-10-13 21:43 UTC by kukulich

2021-10-14 18:29 UTC, Ocramius requested changes

2021-10-14 18:29 UTC, Ocramius commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
This is very much a bummer: no way to avoid autoloading when inspecting default parameters with `new` in them :-\

2021-10-14 18:29 UTC, Ocramius commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
In fact, I'm not sure if `BetterReflection` should stop operating here, and throw an exception :thinking:

2021-10-14 18:39 UTC, kukulich commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
We can also add a method `isDefaultValueAnInitializer()` so everyone can call it as a check and then decide if call `getDefaultValue()`

Second method could be something like `getDefaultValueInitializer()` that could return some object with initializer name and arguments.

2021-10-14 18:46 UTC, Ocramius commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
Will think about it - brain fried for today.

/cc @asgrim this breaks the initial premise of this library, for context.

2021-10-14 19:37 UTC, ondrejmirtes commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
For PHPStan purposes I'd need the AST of the default value and that's sufficient to resolve the type of the value without triggering autoloading.

So the BR's Reflection* classes could offer the AST and the adapter could have getDefaultValue() with the risk of autoloading, which is neccesary for compatibility.

2021-10-22 08:28 UTC, Ocramius commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
Seems viable. Another thing we could do is `getDefaultValue()` throwing an exception when/if the value would lead to autoloading, and having a dedicated method that allows initialization instead.

2021-10-22 08:37 UTC, asgrim commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
Yeh, not sure why we need to initialise here, I'd really like to avoid it totally, since it undermines the whole "static analysis" thing. I'd rather ttake `$className` and run it through whatever configured Source Locators we can pass into here perhaps. I know it is added complexity, but it is complexity borne by these new language features, so is inherent I think

2021-10-22 14:27 UTC, Ocramius commented on src/NodeCompiler/CompileNodeToValue.php
> +                throw Exception\UnableToCompileNode::becauseOfInitializer($context, $node);
Thanks for moving this to an exception for now :-)

2021-10-22 14:32 UTC, kukulich commented on src/NodeCompiler/CompileNodeToValue.php
> +        return new $className(...$arguments);
Now it throws exception. `getAst()` method is already there, so PHPStan should be ok too.

2021-10-22 14:38 UTC, kukulich commented
Ok, can I lower the MSI again? It looks it's already failing in master...

2021-10-22 14:41 UTC, Ocramius commented
@kukulich yes please - I was trying to see which mutants were introducing the problem, but nothing related to this specific patch.

2021-10-22 14:42 UTC, Ocramius commented
To me, it seems like coverage is ignoring `assert()` calls, perhaps we have assertions disabled (by accident) in `.ini` :shrug:

2021-10-22 14:48 UTC, Ocramius approved these changes
LGTM :+1:

2021-10-22 14:49 UTC, kukulich commented
I think the problem is that we use `assert` to make PHPStan/Psalm happy but there are places where the `assert` cannot never fail.

2021-10-22 14:50 UTC, Ocramius commented
@kukulich those should **in theory** be picked up by `roave/infection-static-analysis-plugin`, but since they are uncovered, the plugin never kicks in to squish those mutants.

2021-10-22 15:11 UTC, Ocramius commented
I see you're trying to improve this in #825 - meanwhile, merging here :)

2021-10-22 15:11 UTC, merged