PHP 8.1: Enums
Roave/BetterReflection pull request #827
Opened 2021-10-25 17:59 UTC by kukulich

Fixes #789
Fixes #806

2021-10-25 22:48 UTC, Ocramius requested changes

2021-10-25 22:48 UTC, Ocramius commented on src/Reflection/ReflectionEnum.php
> +class ReflectionEnum extends ReflectionClass
Overall, not a fan of having inheritance here for enums (core has that), but it's not a blocker for 5.x for now.

I'd expect this to probably be broken up in 6.x

2021-10-25 22:48 UTC, Ocramius commented on src/Reflection/ReflectionEnum.php
> +            return null;
We should probably not expose a nullable API in our core here, or we should perhaps get rid of `isBacked()` and `hasCase()`.

2021-10-25 22:48 UTC, Ocramius commented on src/Reflection/ReflectionEnum.php
> +        $backingType = ReflectionNamedType::createFromTypeAndReflector($this->node->scalarType);
`createFromTypeAndReflector` is missing a reflector here

2021-10-26 06:06 UTC, kukulich commented on src/Reflection/ReflectionEnum.php
> +        $backingType = ReflectionNamedType::createFromTypeAndReflector($this->node->scalarType);
https://github.com/Roave/BetterReflection/pull/831

2021-10-26 06:35 UTC, kukulich commented on src/Reflection/ReflectionEnum.php
> +            return null;
`hasCase`/`getCase` - it's same as `hasProperty`/`getProperty` - I tried to use the same pattern.

`getBackingType` - I modified it to the same pattern as `getDefaultValue()`. It now throws exception when enum is not backed.

2021-10-26 17:26 UTC, kukulich commented
@Ocramius @asgrim 

I'm not sure... Should I implement https://3v4l.org/dN6BB as part of `BetterReflectionClass` or only in adapter?

2021-10-27 08:57 UTC, Ocramius commented
> or only in adapter?

Looks like an adapter-only concern, since it causes autoloading :-\

2021-10-27 09:05 UTC, kukulich commented
@Ocramius I think this return value does not need autoload because `enum(Foo::BOO)` is just string. I'm just not sure if BR enum/class should return enum cases in list of constants.

2021-10-27 09:08 UTC, Ocramius commented
```
  ["BOO"]=>
  enum(Foo::BOO)
```

Is that really just a `string`? Looks like the engine is doing more there :thinking:

2021-10-27 09:10 UTC, kukulich commented
@Ocramius Oh, shit. You're right https://3v4l.org/fQiIg :(

2021-10-27 09:10 UTC, kukulich commented
Btw my question is for `getReflectionConstants()` as well.

2021-10-29 06:08 UTC, Ocramius commented
> @Ocramius Oh, shit. You're right https://3v4l.org/fQiIg :(

Yeah, that's kinda what I was referring to - it's actually instantiating the ENUM, so runtime evaluation is quite needed :-\ 

I think it would be potentially acceptable to have that happen in the **adapters**, but not in core (similar to what you did with `new in initializers` in #819 )

2021-10-29 06:11 UTC, Ocramius commented
I think besides dependabot, this is the last one we need to push through for `5.0.0` :O

2021-10-29 06:39 UTC, kukulich commented
@Ocramius This is already ready for review :) `getConstants()` for enum cases is implemented only in adapters

2021-10-29 14:55 UTC, Ocramius commented
@asgrim since I'm off until Wednesday (literally on a trip), can you perhaps help getting this through in the next days? 

Also: let's please not tag `5.0.0` until we tried it with `roave/backward-compatibility-check` (should be few minor changes)

2021-10-29 15:12 UTC, asgrim commented
> @asgrim since I'm off until Wednesday (literally on a trip), can you perhaps help getting this through in the next days?
> 
> Also: let's please not tag `5.0.0` until we tried it with `roave/backward-compatibility-check` (should be few minor changes)

I'm also off until Weds :sweat_smile: I'll see if I can get to it but no promises, quite a beast this one @kukulich :grin:

2021-10-29 15:26 UTC, kukulich commented
@asgrim There are more tests than the code changes 😃

2021-11-05 16:34 UTC, Ocramius approved these changes
Absolutely impeccable! :O 

Impressive work, @kukulich, thank you!

2021-11-05 16:34 UTC, Ocramius commented on src/Reflection/Adapter/ReflectionClass.php
> +            $reflectionConstants += $this->betterReflectionClass->getCases();
Not a fan of `+=`, but we'll make it work :D

2021-11-05 16:34 UTC, merged